export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  // ── Ego check ──
  { text: "You're not tired. You're just uncomfortable.", author: "Unknown" },
  { text: "Your excuses are exactly as creative as your results.", author: "Unknown" },
  { text: "You've been 'about to start' for months.", author: "Unknown" },
  { text: "Stop performing productivity. Start doing the actual work.", author: "Unknown" },
  { text: "You know what to do. You're just scared of how good you could become.", author: "Unknown" },
  { text: "Discipline is not a personality trait. It's a decision you keep making.", author: "Unknown" },
  { text: "You have the same hours as everyone you admire.", author: "Unknown" },
  { text: "You can have results or excuses. Not both.", author: "Unknown" },
  { text: "Your standards determine your outcomes.", author: "Unknown" },
  { text: "The world doesn't reward intentions.", author: "Unknown" },
  { text: "Motivation is for amateurs. Professionals just show up.", author: "Unknown" },
  { text: "What you tolerate, you teach.", author: "Unknown" },
  { text: "You don't need inspiration. You need a decision.", author: "Unknown" },
  { text: "The gap between who you are and who you want to be is called discipline.", author: "Unknown" },
  { text: "Nothing changes if nothing changes.", author: "Unknown" },
  { text: "Results don't lie.", author: "Unknown" },
  { text: "Stop waiting to feel ready. You never will.", author: "Unknown" },
  { text: "Inaction is also a choice.", author: "Unknown" },
  { text: "Excellence is a habit. So is mediocrity.", author: "Unknown" },
  { text: "Average effort produces average results.", author: "Unknown" },
  { text: "What you do in private determines what you achieve in public.", author: "Unknown" },
  { text: "You're not too busy. You're just not prioritizing.", author: "Unknown" },
  { text: "Suffer the pain of discipline or the pain of regret.", author: "Unknown" },
  { text: "Do less, but do it completely.", author: "Unknown" },
  { text: "The most dangerous phrase is 'I'll start Monday.'", author: "Unknown" },
  { text: "Your comfort zone has an expiry date.", author: "Unknown" },
  { text: "The version of you that you keep putting off is getting impatient.", author: "Unknown" },
  { text: "You're building something or you're building excuses. Pick one.", author: "Unknown" },
  { text: "Nobody is coming to save you.", author: "Unknown" },
  { text: "Your potential is insulted by the effort you're giving it.", author: "Unknown" },
  { text: "Every day you delay is a vote against yourself.", author: "Unknown" },
  { text: "The hardest part isn't starting. It's not quitting.", author: "Unknown" },
  { text: "You are the only project that matters. Act like it.", author: "Unknown" },
  { text: "Your future self is watching. What are you showing them?", author: "Unknown" },
  { text: "Comfort is the enemy dressed as a reward.", author: "Unknown" },
  { text: "You don't have bad luck. You have bad habits.", author: "Unknown" },
  { text: "The person you want to be requires the person you are to change.", author: "Unknown" },
  { text: "Stop explaining yourself to people who aren't paying your bills.", author: "Unknown" },
  { text: "What you accept today becomes your standard tomorrow.", author: "Unknown" },
  { text: "Most people want the result but avoid the process. That's why most people don't get results.", author: "Unknown" },

  // ── Philosophy ──
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "Clarity comes from action, not thought.", author: "Marie Forleo" },
  { text: "Being busy is a modern form of laziness.", author: "Tim Ferriss" },
  { text: "The obstacle is the way.", author: "Marcus Aurelius" },
  { text: "One percent better every day is 37× better in a year.", author: "James Clear" },
  { text: "If it's important, do it every day.", author: "Dan Gable" },
  { text: "Small actions, compounded daily, become unrecognizable results.", author: "Unknown" },
  { text: "Your life is the sum of what you focus on.", author: "Unknown" },
  { text: "Show up when you don't feel like it. That's where character is built.", author: "Unknown" },
  { text: "The master has failed more times than the beginner has tried.", author: "Unknown" },
  { text: "Every pro was once an amateur who didn't quit.", author: "Unknown" },
  { text: "Success is not an event. It's a habit.", author: "Unknown" },
  { text: "If you're not growing, you're decaying.", author: "Unknown" },
  { text: "A year from now, you'll wish you started today.", author: "Karen Lamb" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Aristotle" },
  { text: "Fall seven times, stand eight.", author: "Japanese Proverb" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary" },
  { text: "The price of not following your dream is having to work for someone who did.", author: "Unknown" },
  { text: "The price of anything is the amount of life you exchange for it.", author: "Henry David Thoreau" },
  { text: "You don't rise to your goals. You fall to your systems.", author: "James Clear" },
  { text: "The quality of your life is the quality of your questions.", author: "Tony Robbins" },
  { text: "Action is the antidote to despair.", author: "Joan Baez" },
  { text: "Overnight success is a 10-year story edited for Instagram.", author: "Unknown" },
  { text: "Vision without execution is daydreaming.", author: "Unknown" },

  // ── Uncomfortable truths ──
  { text: "Your dream is not special if you're not working on it daily.", author: "Unknown" },
  { text: "The reason you haven't changed is that you haven't decided to.", author: "Unknown" },
  { text: "You're not overwhelmed. You're undisciplined.", author: "Unknown" },
  { text: "Busy is not the same as productive.", author: "Unknown" },
  { text: "Tired is temporary. Regret is permanent.", author: "Unknown" },
  { text: "The problem isn't time. It's priorities.", author: "Unknown" },
  { text: "You're not failing because you lack talent. You're failing because you lack consistency.", author: "Unknown" },
  { text: "Scrolling is not resting. It's avoiding.", author: "Unknown" },
  { text: "You can't think your way into better habits. You act your way in.", author: "Unknown" },
  { text: "Low output is a choice masquerading as circumstance.", author: "Unknown" },
  { text: "The version of you who makes excuses will always underperform the one who just does the work.", author: "Unknown" },
  { text: "Wanting is not the same as choosing.", author: "Unknown" },
  { text: "Every time you skip, you're teaching yourself that skipping is acceptable.", author: "Unknown" },
  { text: "You're not stuck. You're comfortable.", author: "Unknown" },
  { text: "Hard work doesn't guarantee success. Not working hard guarantees failure.", author: "Unknown" },
  { text: "You compare your effort to your peers and your results to your heroes. That's the problem.", author: "Unknown" },
  { text: "Motivation gets you started. Discipline keeps you going when it stops.", author: "Unknown" },
  { text: "If you won't do it on your worst day, your best day is just luck.", author: "Unknown" },
  { text: "Nobody remembers your intention. They remember your output.", author: "Unknown" },
  { text: "Your sensitivity to criticism grows in proportion to how little work you're doing.", author: "Unknown" },

  // ── Identity and growth ──
  { text: "You don't find yourself. You build yourself.", author: "Unknown" },
  { text: "Identity is built by keeping promises to yourself.", author: "Unknown" },
  { text: "Who you are is decided by what you do when no one is watching.", author: "Unknown" },
  { text: "You can't outwork a bad identity. Fix who you think you are first.", author: "Unknown" },
  { text: "Character is what you do at rep nine when you planned for eight.", author: "Unknown" },
  { text: "Confidence is not given to you. It is built.", author: "Unknown" },
  { text: "You become your habits before you become your goals.", author: "Unknown" },
  { text: "The life you want is on the other side of the person you haven't become yet.", author: "Unknown" },
  { text: "Every choice is a vote for the person you are becoming.", author: "James Clear" },
  { text: "Stop waiting for permission. Nobody is coming to grant it.", author: "Unknown" },
  { text: "Growth is just sustained discomfort you didn't run from.", author: "Unknown" },
  { text: "You are not your feelings. You are your actions.", author: "Unknown" },
  { text: "The strongest version of you exists on the other side of today's resistance.", author: "Unknown" },
  { text: "Most people negotiate with their alarm clock. Winners don't.", author: "Unknown" },
  { text: "You have potential. Everyone does. Potential without action is just potential.", author: "Unknown" },
  { text: "The first step is always the hardest. The second is habit.", author: "Unknown" },
  { text: "You're not behind. You're exactly where your decisions have put you.", author: "Unknown" },
  { text: "Stop performing the idea of work. Do the actual work.", author: "Unknown" },

  // ── Sharp and short ──
  { text: "Discipline is freedom.", author: "Jocko Willink" },
  { text: "Earn it.", author: "Unknown" },
  { text: "Outwork your excuses.", author: "Unknown" },
  { text: "Today or never.", author: "Unknown" },
  { text: "Less talk. More output.", author: "Unknown" },
  { text: "No shortcuts. No shortcuts.", author: "Unknown" },
  { text: "Your life is your argument.", author: "Unknown" },
  { text: "Pain now or pain later. Choose.", author: "Unknown" },
  { text: "The work is the reward.", author: "Unknown" },
  { text: "Done beats perfect.", author: "Unknown" },
  { text: "Start before you're ready.", author: "Unknown" },
  { text: "Be the reason you succeed.", author: "Unknown" },
  { text: "No one is going to want it for you.", author: "Unknown" },
  { text: "Your potential needs your effort to exist.", author: "Unknown" },
  { text: "Suffer now, live later.", author: "Unknown" },
  { text: "Compete with who you were yesterday.", author: "Unknown" },
  { text: "The shortcut is the long way.", author: "Unknown" },

  // ── Unconventional ──
  { text: "Ambition without discipline is a fantasy with a deadline.", author: "Unknown" },
  { text: "The most radical thing you can do is keep going.", author: "Unknown" },
  { text: "Your biggest competition is the version of you that keeps quitting.", author: "Unknown" },
  { text: "Speed is irrelevant if you're going in the wrong direction.", author: "Unknown" },
  { text: "Not all progress is visible. Some of it is you not quitting.", author: "Unknown" },
  { text: "Self-discipline is self-respect made visible.", author: "Unknown" },
  { text: "There is no version of greatness that doesn't include boredom.", author: "Unknown" },
  { text: "You will always find time for what you truly prioritize.", author: "Unknown" },
  { text: "Most advice is autobiography. Take it with that filter.", author: "Unknown" },
  { text: "The goal isn't to feel motivated. The goal is to be effective.", author: "Unknown" },
  { text: "A good plan executed now beats a perfect plan executed never.", author: "Unknown" },
  { text: "Procrastination is just fear with better PR.", author: "Unknown" },
  { text: "Perfection is just procrastination with a good excuse.", author: "Unknown" },
  { text: "Urgency is a skill, not a feeling.", author: "Unknown" },
  { text: "People don't lack time. They lack commitment.", author: "Unknown" },
  { text: "The most expensive thing in the world is a missed opportunity.", author: "Unknown" },
  { text: "Your story isn't written by your intentions. It's written by your actions.", author: "Unknown" },
  { text: "Most people are waiting for a sign. The sign is today.", author: "Unknown" },
  { text: "You're allowed to be a beginner. You're not allowed to stay one forever.", author: "Unknown" },
  { text: "Obsession is just commitment that makes other people uncomfortable.", author: "Unknown" },

  // ── Accountability ──
  { text: "The person avoiding the process is also avoiding the result.", author: "Unknown" },
  { text: "You're not unlucky. You're unprepared.", author: "Unknown" },
  { text: "Take responsibility. It's the only power you fully own.", author: "Unknown" },
  { text: "Blame is borrowed confidence. Own your situation instead.", author: "Unknown" },
  { text: "Nobody who achieved anything did it by accident.", author: "Unknown" },
  { text: "If you're not where you want to be, be honest about why.", author: "Unknown" },
  { text: "The only sustainable motivation is becoming someone who doesn't need it.", author: "Unknown" },
  { text: "Stop outsourcing your discipline to motivation.", author: "Unknown" },
  { text: "You chose comfort over growth so often it became your identity.", author: "Unknown" },
  { text: "At some point, the excuses stop being reasons and start being choices.", author: "Unknown" },
  { text: "Own your morning. Own your life.", author: "Unknown" },
  { text: "Discipline creates options. Laziness removes them.", author: "Unknown" },
  { text: "You have everything you need except follow-through.", author: "Unknown" },
  { text: "Your past performance is not your future capability. But your current habits are.", author: "Unknown" },
  { text: "If you can't keep promises to yourself, you can't keep them to anyone.", author: "Unknown" },
  { text: "Your excuses are detailed. Your plans are vague. Fix that.", author: "Unknown" },

  // ── Deep cuts ──
  { text: "Most people are living someone else's definition of success.", author: "Unknown" },
  { text: "The uncomfortable truth is you already know what you need to do.", author: "Unknown" },
  { text: "You don't need more information. You need more execution.", author: "Unknown" },
  { text: "Reading about discipline doesn't make you disciplined.", author: "Unknown" },
  { text: "Your potential laughs at your comfort zone.", author: "Unknown" },
  { text: "Most regret comes not from trying and failing, but from not trying.", author: "Unknown" },
  { text: "You've been waiting for the right moment for so long the moment has passed.", author: "Unknown" },
  { text: "The gap between knowing and doing is where most people live.", author: "Unknown" },
  { text: "What if you spent as much energy on your goals as on your excuses?", author: "Unknown" },
  { text: "Your discipline is a message you send to yourself every morning.", author: "Unknown" },
  { text: "Feeling unprepared is not the same as being unprepared. Go anyway.", author: "Unknown" },
  { text: "The version of you that complains and the version that executes cannot coexist.", author: "Unknown" },
  { text: "You can outlast almost anyone if you refuse to stop.", author: "Unknown" },
  { text: "The day you stop making excuses is the day your life changes.", author: "Unknown" },
  { text: "Your goals don't care about your mood.", author: "Unknown" },

  // ── Borrowed wisdom ──
  { text: "The price of not following your dream is having to work for someone who did.", author: "Unknown" },
  { text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { text: "You don't have to be great to start. But you have to start to be great.", author: "Zig Ziglar" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The secret is there is no secret. Only hard work.", author: "Unknown" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "You are confined only by the walls you build yourself.", author: "Andrew Murphy" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Courage is not the absence of fear but the decision that something else matters more.", author: "Unknown" },
  { text: "The secret to success is to do the common things uncommonly well.", author: "John D. Rockefeller" },
  { text: "Champions are made from something deep inside — a desire, a dream, a vision.", author: "Muhammad Ali" },
  { text: "Dream big. Start small. Begin now.", author: "Unknown" },
  { text: "The will to win means nothing without the will to prepare.", author: "Juma Ikangaa" },
  { text: "You don't get what you wish for. You get what you work for.", author: "Unknown" },
  { text: "The graveyard is the richest place on earth — full of potential never acted on.", author: "Unknown" },
  { text: "Stop rehearsing failure in your head and start rehearsing execution.", author: "Unknown" },
  { text: "What you repeatedly do is what you ultimately become.", author: "Unknown" },
  { text: "If your habits don't match your goals, your goals are just wishes.", author: "Unknown" },
  { text: "The standard you walk past is the standard you accept.", author: "Unknown" },
  { text: "One more rep. One more page. One more hour. That's how it's won.", author: "Unknown" },
];

// Returns a random quote on every call — different each page load.
export function getCurrentQuote(): Quote {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)]!;
}
