// ─── Context Builder ───────────────────────────────────────────────────────────
// Assembles the dynamic layer (≤ 2,000 tokens) and micro-prompt (≤ 300 tokens)
// that the Response Brain receives alongside the static layer.
// SKILL.md §5.3: dynamic layer is generated by code, not LLM.
// Owner: Context Builder. No LLM calls.

import type { NovaContext } from "../types/context.types";
import type { InterventionName } from "../types/intervention.types";
import type { DecisionGraphOutput } from "../types/response.types";
import { OPERATING_STYLE_HEADER } from "../../personality/signal-scoring";

// ── Token budget constants ────────────────────────────────────────────────────
// Rough character-per-token estimate for English: ~4 chars/token.
// We target 2,000 tokens for dynamic layer = ~8,000 chars.
// Micro-prompt: 300 tokens = ~1,200 chars.

const MAX_DYNAMIC_CHARS  = 7_500;
const MAX_MICRO_CHARS    = 1_100;

// ── Section builders ──────────────────────────────────────────────────────────

function buildStudentSection(ctx: NovaContext): string {
  const p     = ctx.userProfile;
  const state = ctx.academicState;

  const lines: string[] = [
    `## Student`,
    `Name: ${p.displayName}`,
    `Year: ${p.yearOfStudy ?? "unknown"} | Major: ${p.major ?? "unknown"} | Institution: ${p.institution ?? "unknown"}`,
    `Joined: ${state.daysSinceJoined}d ago | Subjects: ${p.subjects.join(", ") || "none yet"}`,
  ];
  if (ctx.operatingStyle && ctx.operatingStyle.length > 0) {
    lines.push(OPERATING_STYLE_HEADER, ...ctx.operatingStyle.map(l => `- ${l}`));
  }
  return lines.join("\n");
}

function buildStateSection(ctx: NovaContext): string {
  const s = ctx.academicState;
  const d = s.hardDirectives;

  const lines: string[] = [
    `## Academic State`,
    `Phase: ${s.semesterPhase} | Mode: ${s.activeMode} | Momentary: ${s.momentaryState}`,
    `Scores — Engagement:${s.scores.engagement} Confidence:${s.scores.confidence} Momentum:${s.scores.momentum} BurnoutRisk:${s.scores.burnoutRisk} Adherence:${s.scores.planAdherence}`,
    `Streak: ${s.studyStreakDays}d | Since last session: ${s.daysSinceLastSession}d | Misses: ${s.consecutiveMisses}`,
  ];

  if (s.daysUntilNextExam !== null) {
    lines.push(`Exam in: ${s.daysUntilNextExam} days`);
  }

  const activeDirectives = Object.entries(d)
    .filter(([_, v]) => v)
    .map(([k]) => k)
    .join(", ");
  if (activeDirectives) {
    lines.push(`ACTIVE DIRECTIVES: ${activeDirectives}`);
  }

  return lines.join("\n");
}

function buildUnderstandingSection(ctx: NovaContext): string {
  const u = ctx.understanding;
  const lines: string[] = [
    `## This Message`,
    `Intent: ${u.intent} | Emotion: ${u.emotion} | Disclosure: ${u.disclosureClass}`,
    `Topic: ${u.topic ?? "none"} (confidence: ${(u.topicConfidence * 100).toFixed(0)}%)`,
    `Ambiguity: ${(u.ambiguityScore * 100).toFixed(0)}% | Routing: ${u.routingSignal}`,
    `Text: "${ctx.rawMessage.slice(0, 200)}"`,
  ];
  return lines.join("\n");
}

function buildMemorySection(ctx: NovaContext): string {
  if (ctx.topRelevantMemories.length === 0) return "";

  const lines = [
    `## Relevant Memories (top ${Math.min(3, ctx.topRelevantMemories.length)})`,
    ...ctx.topRelevantMemories.slice(0, 3).map(m =>
      `- [${m.factType}] ${m.value} (${(m.confidence * 100).toFixed(0)}%)`
    ),
  ];

  if (ctx.contrastiveMemories.length > 0) {
    lines.push(`\nContrastive:`);
    lines.push(...ctx.contrastiveMemories.slice(0, 2).map(m =>
      `- ${m.value}`
    ));
  }

  return lines.join("\n");
}

function buildKnowledgeSection(ctx: NovaContext): string {
  const parts: string[] = [];

  if (ctx.topicMastery) {
    const t = ctx.topicMastery;
    parts.push([
      `## Topic: ${t.topicName} (${t.subjectName})`,
      `Mastery: ${(t.masteryProbability * 100).toFixed(0)}% | Retention: ${(t.retentionEstimate * 100).toFixed(0)}%`,
      `Self-confidence: ${(t.confidenceReported * 100).toFixed(0)}% | Gap: ${(t.calibrationGap * 100).toFixed(0)}% | Trend: ${t.masteryTrend}`,
      `Reviews: ${t.reviewCount} | Last: ${t.lastStudied ? `${Math.floor((Date.now() - t.lastStudied.getTime()) / 86_400_000)}d ago` : "never"}`,
    ].join("\n"));
  }

  if (ctx.examContext) {
    const e = ctx.examContext;
    parts.push([
      `## Exam: ${e.examTitle} (${e.subjectName})`,
      `In ${e.daysUntil} days | Mode: ${e.mode} | Focus: ${e.primaryFocus}`,
      `Critical topics: ${e.riskMatrix.critical.join(", ") || "none"}`,
      `Recommended: ${e.recommendedDailyHours}h/day`,
    ].join("\n"));
  }

  if (ctx.studyPlan && ctx.studyPlan.today.length > 0) {
    const p = ctx.studyPlan;
    const blocks = p.today.slice(0, 3).map(b =>
      `  - ${b.topicName} (${b.durationMinutes}min, ${b.activityType}, ${b.urgency})`
    );
    parts.push([
      `## Today's Plan (${p.totalMinutesToday}min total, confidence: ${(p.confidence * 100).toFixed(0)}%)`,
      ...blocks,
    ].join("\n"));
  }

  return parts.join("\n\n");
}

function buildActiveSessionSection(ctx: NovaContext): string {
  // Prefer richer sessionContext if available; fall back to raw activeSession
  const sc = ctx.sessionContext;
  if (!sc && !ctx.activeSession) return "";

  const action = ctx.sessionAction;
  const parts: string[] = [];

  if (sc) {
    const status = sc.isPaused ? "PAUSED" : "ACTIVE";
    const plan   = sc.plannedDurationMinutes > 0
      ? `${sc.elapsedMinutes}/${sc.plannedDurationMinutes}min`
      : `${sc.elapsedMinutes}min elapsed`;

    parts.push(`## Study Session [${status}]`);
    parts.push(
      `Topic: ${sc.topicName ?? "unspecified"} | Subject: ${sc.subjectName ?? "unknown"} | ${plan}`
    );

    if (sc.currentFocus) parts.push(`Focus: ${sc.currentFocus}`);
    if (sc.confusionPoints.length > 0) {
      parts.push(`Confusion so far: ${sc.confusionPoints.slice(0, 3).join(", ")}`);
    }
    if (sc.topicsCompleted.length > 0) {
      parts.push(`Completed: ${sc.topicsCompleted.join(", ")}`);
    }
    if (sc.pauseCount > 0) parts.push(`Pauses: ${sc.pauseCount}`);
    parts.push(
      `Mastery estimate: ${(sc.masteryEstimate * 100).toFixed(0)}% | Energy: ${sc.energyLevel ?? "unknown"}`
    );
  } else if (ctx.activeSession) {
    const s       = ctx.activeSession;
    const elapsed = Math.floor((Date.now() - s.startedAt.getTime()) / 60_000);
    parts.push(`## Study Session [ACTIVE]`);
    parts.push(`Topic: ${s.topicName ?? "unspecified"} | Elapsed: ${elapsed}min`);
  }

  // Session action instruction for Response Brain
  if (action) {
    const INSTRUCTIONS: Record<string, string> = {
      explain_topic:       `EXPLAIN ${action.topicName ?? "the current topic"} clearly and concisely. Then check if it makes sense.`,
      focus_intervention:  `Student is distracted. Acknowledge without judgment. Give one concrete refocus technique. Then remind them what they were doing.`,
      next_task:           `Student finished the current topic or is asking what's next. Suggest the next logical topic or exercise based on their plan/mastery.`,
      break_recommendation: `Student needs a break. Affirm it. Suggest a specific short break (5–10min). Tell them exactly where to resume when they're back.`,
      adapt_session:       `Student already knows ${action.topicName ?? "this topic"}. Acknowledge it, then suggest moving to the next challenging topic.`,
      planner_adapt:       `Student is behind or checking progress. Acknowledge where they are, adjust expectations honestly, and give them a prioritised next step.`,
      resume_session:      `Student is back from break. Welcome them back briefly. Remind them where they left off and what the next task is.`,
      end_session:         `Student finished studying. Produce a brief reflection prompt: what did they cover? How did it feel? What's one thing they learned?`,
      continue:            `Student is mid-session and checking in. Respond in the context of their current study — brief, focused, encouraging.`,
    };
    parts.push(`\n## Session Action: ${action.type.toUpperCase()}`);
    parts.push(INSTRUCTIONS[action.type] ?? `Handle: ${action.type}`);
  }

  return parts.join("\n");
}

function buildPatternSection(ctx: NovaContext): string {
  const dominant = ctx.patterns.dominantPattern;
  if (!dominant || dominant.severity === "emerging") return "";

  return [
    `## Detected Pattern: ${dominant.type} (${dominant.severity})`,
    `Confidence: ${(dominant.confidence * 100).toFixed(0)}% | Occurrences: ${dominant.occurrences}`,
    `Recommendation: ${dominant.recommendation}`,
  ].join("\n");
}

function buildCognitiveStateSection(ctx: NovaContext): string {
  const cog = ctx.cognitiveState;
  if (!cog.investigationTopic || !cog.investigationStatus) return "";

  return [
    `## Active Investigation`,
    `Topic: ${cog.investigationTopic} | Status: ${cog.investigationStatus} | Attempts: ${cog.investigationAttempts}`,
    cog.investigationHypotheses.length > 0
      ? `Hypotheses: ${cog.investigationHypotheses.slice(0, 2).join("; ")}`
      : "",
  ].filter(Boolean).join("\n");
}

function buildConversationHistorySection(ctx: NovaContext): string {
  const recent = ctx.conversationHistory.slice(-4);
  if (recent.length === 0) return "";

  const lines = [
    `## Recent Conversation`,
    ...recent.map(t =>
      `${t.role === "user" ? "Student" : "Nova"}: ${t.text.slice(0, 120)}`
    ),
  ];
  return lines.join("\n");
}

// ── Dynamic layer assembly ─────────────────────────────────────────────────────

export function buildDynamicLayer(ctx: NovaContext): string {
  const sections = [
    buildStudentSection(ctx),
    buildStateSection(ctx),
    buildUnderstandingSection(ctx),
    buildActiveSessionSection(ctx),
    buildMemorySection(ctx),
    buildKnowledgeSection(ctx),
    buildPatternSection(ctx),
    buildCognitiveStateSection(ctx),
    buildConversationHistorySection(ctx),
  ].filter(Boolean);

  let assembled = sections.join("\n\n");

  // Truncate if over budget (last resort — shouldn't happen with proper section limits)
  if (assembled.length > MAX_DYNAMIC_CHARS) {
    assembled = assembled.slice(0, MAX_DYNAMIC_CHARS) + "\n[...context truncated]";
  }

  return assembled;
}

// ── Micro-prompt (intervention + evidence) ────────────────────────────────────

const MICRO_PROMPT_TEMPLATES: Record<InterventionName, string> = {
  empathize:             "Acknowledge the emotional weight first. Don't pivot to academics yet. Keep it short — 1-2 sentences max.",
  challenge:             "Gently but directly challenge the excuse or avoidance. Don't soften it too much. Be brief.",
  accountability:        "Hold them to what they said they'd do. Keep the tone firm but caring. No lecturing.",
  refocus:               "Redirect back to study focus without ignoring their current state. What's the next concrete step?",
  clarify:               "You need more info before responding. Ask exactly one clarifying question. Nothing else.",
  problem_solve:         "Give a practical, actionable response. Max 3 concrete steps. Skip theory.",
  reduce_friction:       "Reduce the barrier. Give them the smallest possible first step. No judgment.",
  reinforce_identity:    "Reinforce who they ARE as a student — their identity, not just their action. Tie it to something specific they said or did.",
  surface_breakthrough:  "Invite them to explore the insight themselves. Ask a question that opens reflection.",
  surface_commitment:    "Get them to commit to one specific thing. Make it small, concrete, and near-term.",
  anchor_commitment:     "Lock in the commitment they just made. Who, what, when. Specifics only.",
  celebrate_win:         "Celebrate the win without overdoing it. Keep the energy going. One sentence of celebration, then forward momentum.",
  reframe_failure:       "Reframe the miss — not as failure, but as data. What does it tell them? Keep it honest.",
  prevent_spiral:        "Interrupt the downward spiral. Ground them in the present. Offer one concrete thing they can do RIGHT NOW.",
  prevent_burnout:       "Back off the pressure. Let them breathe. Suggest rest as a strategic choice, not surrender.",
  momentum_push:         "They're building momentum. Push them to go further. Raise the bar slightly.",
  consistency_check:     "Check in on their actual plan adherence — be direct, not nagging.",
  goal_alignment:        "Reconnect to the bigger picture. Why are they doing this? One pointed question.",
  calibration_check:     "There's a gap between how confident they feel and what their mastery shows. Surface it gently but clearly.",
  crisis_redirect:       "This sounds serious. Acknowledge it. Don't try to fix it academically. If they're in distress, say: 'This sounds like a lot — if you need to talk to someone, please do. I'm an academic coach and that's my limit.'",
  re_engagement:         "They're back after a gap. Make it easy. Don't reference the gap with judgment. Help them start small.",
};

export function buildMicroPrompt(
  decision:  DecisionGraphOutput,
  ctx:       NovaContext,
): string {
  const template  = MICRO_PROMPT_TEMPLATES[decision.selectedIntervention];
  const evidence  = decision.reason;
  const studentMsg = ctx.rawMessage.slice(0, 200);

  const prompt = [
    `Student message: "${studentMsg}"`,
    ``,
    `Selected approach: ${decision.selectedIntervention}`,
    `Evidence: ${evidence}`,
    ``,
    `Instruction: ${template}`,
  ].join("\n");

  if (prompt.length > MAX_MICRO_CHARS) {
    return prompt.slice(0, MAX_MICRO_CHARS);
  }
  return prompt;
}
